trigger:
  branches:
    include:
      - main
  paths:
    include: 
      - /variables/variables-ex1.yml

pool:
  vmImage: ubuntu-latest

variables:      # pipeline-level
 MY_VAR: 'my value'
 ANOTHER_VAR: 'another value'

stages:
- stage: Build
  variables:    # stage-level
    STAGE_VAR: 'that happened'
    NAME: Anas
  jobs:
  - job: FirstJob
    template: /variables/main-variable.yml
    variables:  # job-level
      JOB_VAR: $(var1)
    steps:
    - script: echo $(MY_VAR) $(STAGE_VAR) $(JOB_VAR)
  - job: SecondJob
    variables:
      JOB_VAR: 'jo var' 

- stage: Test
  variables:    # stage-level
    STAGE_VAR: 'that happened'

  jobs:
  - job: FirstJob
    variables:  # job-level
      JOB_VAR: 'a job var'
    steps:
    - script: echo $(MY_VAR) $(STAGE_VAR) $(JOB_VAR)  
    - script: echo $(NAME)  